app/index.html

Google Maps Language localization

---

app/js/globals.js

No card quando aparece o nome do tipo de bicicletário fica como "Bicicletário De roda". 
Mudando para ficar "Bicicletário de Roda"

mudança p caixa-baixa no tipo 'de Roda'

---

app/js/app.js

Adicionei a url de novo e filtro a condição do roteador.

Added new urls to fix router

---

app/js/app.js

Separei a parte do bikelayer em uma função separada, para depois criar um modulo de mapas que vai gerenciar todas interações com o mapa.

Changing bikelanes layer to function

---

app/index.html
app/js/app.js

Adapted template and app.js to have microdata in markers details.

Improve SEO with Microdata

---

app/js/Map.js

Fixing the init behaviour to show user pin only after he used geolocation for the first time

fix map init

---

app/js/Geolocation.js
app/js/Map.js

Fix geolocation and map code for the original functionality.
Watcher now will no longer center map.

Fix Watcher

---

app/js/app.js

Fixing when the GA event should be called.

Fix event behavior for geolocation watcher

---

app/js/Geolocation.js
app/js/Map.js
app/js/app.js

Fix behaviour to start map on marker's location from deeplink

(Topic-54) - Start map on Marker's location from deeplink

---

app/js/Geolocation.js
app/js/Map.js

Tava estudando JS e parei para dar uma passada e olho no código e ver o que eu poderia mudar rapidamente. 
- Mudei de cons para let arrays que eram modificados após sua criação já que const é read only.
- Alterei a definição de parâmetros na geolocalização para object.assign pra ficar mais legível. 
- Criei o clearWatch no geolocation por que o voltar para porto alegre retornava o usuario pra localização dele em alguns casos.

Code Refactoring + clearWatch

---

app/js/Map.js
assets/img/last_position.svg

Changed map init geolocation to use the same method from the map module.
Changed names for user maker location to indicated that is user marker's instead of any marker since we have logic for other markers inside the module.
Add an svg icon to last location. 
changed user marker initialization and created a method do change the icon based on whether geolocation is up or is the last location we have.

topic-59: Icon for cached location

---

app/index.html
app/js/app.js

Include a data-src in img element to revert to it on logout.
verify ismobile to hide the button

Topic-38: fix logout ui in mobile

---

app/js/Geolocation.js
app/js/Map.js
app/js/app.js
app/js/globals.js

Rewrite the entire initiazitation of map module to receive default location from app.js
Moved google dependancies from geolocation module to maps

Topic-74: Fixed bug with starting location.

---

app/js/Map.js
app/js/app.js

- Adiciona de volta a funcao de callback que sumiu no último refactor do componente de mapa.
- Corrige problemas de identação sugeridos pelo ESlint.
- Move searchAdress() pra dentro da classe.

Fixes bug with missing parameter on map init

---

app/js/Map.js
app/js/app.js

A Hannah deu essa ideia aleatoriamente esses dias: trackear qual a distancia que os bicicletarios que a pessoa vê estão dela mesma.
Gerar estatisticas disso pode nos trazer insights interessantes, como por exemplo se as pessoas usam mais o bike de boa pra encontrar bicicletarios quando já estão na rua, ou se usam ele mais pra se planejar.

Creates new GA event: distance from user

---

app/js/Map.js

Added a verification on map init to not create the user marker on map center on location defaults

Fix 74 map init

---

app/js/Map.js
app/js/app.js
app/js/globals.js

Discutimos sobre isso mas acabei esquecendo de implementar hehe

Limit max distance to fit to viewport

---

app/dashboard.html
app/js/Database.js
app/js/User.js
app/js/app.js
app/scss/main.scss
app/templates/placeDetailsContent.hbs

> **Importante**: este PR deve ir pra produção ao mesmo tempo que https://github.com/dennerevaldt/bikedeboa-api/pull/16
- Muda a lógica de como testamos se o usuário tem permissão para editar e deletar bicicletários (issue https://github.com/cmdalbem/bikedeboa/issues/92).
- Exige login para deixar avaliações (issue https://github.com/cmdalbem/bikedeboa/issues/52).
- Melhora design do card com as perguntas em aberto (screenshot abaixo).
- Melhora design da barrinha de "sua avaliação" pra aumentar a proeminência desta seção. (screenshot abaixo)
- Muda levemente o texto da modal de login pra incentivar mais a colaboração (2a screenshot).
- Resolve bug antigo sobre deeplinks e login. (Quando o usuário abria um bicicletário através de deeplink a modal muito provavelmente abria antes que o …

Revisa permissões para editar e avaliar bicicletários

---

app/js/Map.js
app/js/app.js
app/scss/main.scss
app/templates/newPlaceModal.hbs

Implementa a issue https://github.com/cmdalbem/bikedeboa/issues/30

Add new place name suggestion based on nearby POIs

---

app/dashboard.html
app/js/app.js
app/scss/main.scss
app/templates/newPlaceModal.hbs
app/templates/placeDetailsContent.hbs
assets/img/icon_photo_white.svg

_Essa é uma ideia que eu tava há muuuito tempo na cabeça, to feliz de ter finalmente implementado ela mas não tenho 100% certeza do Design ainda_
A ideia é incentivar usuários **logados** a adicionar fotos dos bicicletários quando não tem.
Mais do que simplesmente ter a edição de bicicletários habilitada pra qualquer usuário logado, eu queria trazer já na modal de detalhes uma "chamada" que incentive o usuário. Decidi fazer isso usando como background uma foto do Street View daquele mesmo lugar. Mesmo usando a exata localização do bicicletário no Street View e configurando angulo de camera pra tentar capturar o local exato da calçada, eu sei que muitas vezes isso não vai funcionar, por isso a imagem só é usada no fundo, como um "teaser" pra chamar a atenção do usuário e incentivá-lo a …

Banner que incentiva usuário a adicionar foto

---

.eslintrc.js
app/dashboard.html
app/js/Database.js
app/js/Geolocation.js
app/js/Map.js
app/js/Places.js
app/js/app.js
app/js/globals.js
app/js/utils.js
app/scss/main.scss

A Hannah tava brincando com os filtros e descobriu que eles tavam funcionando meio estranho. Olhando o código vi uma série de problemas relacionados a como guardamos o array de bicicletários e o array de pins do Maps.
Este PR resolve esse problema ao mesmo tempo que dá uma refatorada por cima, mudando o nome do nosso array global `markers` pra `places`, porque na real aqueles não são os pins e sim os bicicletários. Também adicionei uma referência dentro do bicicletário ao pin correspondente a ele.

Fix filters behaving weird

---

app/js/Database.js
app/js/app.js
app/scss/main.scss
app/templates/dataModal.hbs
app/templates/placeDetailsContent.hbs

Melhoramentos sobre Dados
===
Maior proeminência da informação na janela de detalhes dos bicicletários
===

More transparent disclaimers on data sources

---

app/js/Map.js
app/js/app.js
app/js/globals.js

Moved boundaries to globals to make it easier to implement the Mubi project and internationalisation.

Moved boundaries to globals
